/** Specialities that are banned from display because they are irrelevant in this app */
export const BANNED_TRAININGS = [
    'Cytopathologie',
    'Pratique du laboratoire au cabinet médical',
    'Qualification pour les ex. radiologiques à fortes doses en cardiologie',
    'Qualification pour les examens radiologiques à fortes doses'
];

/** All available medical specialities */
export const SPECIALITIES = [
    'Médecin généraliste',
    'Gynécologie et obstétrique',
    'Pédiatrie',
    'Psychiatrie et psychothérapie',
    "Psychiatrie et psychothérapie d'enfants et d'adolescents",
    'Ophtalmologie',
    'Médecine tropicale et médecine des voyages',
    'Neurologie',
    'Pneumologie',
    'Médecine du travail',
    'Dermatologie et vénéréologie',
    'Neurologie',
    'Pneumologie',
    "Chirurgie orthopédique et traumatologie de l'appareil locomoteur",
    'Allergologie et immunologie clinique',
    'Chirurgie plastique, reconstructive et esthétique',
    'Chirurgie cardiaque et vasculaire thoracique',
    'Cardiologie',
    'Orthodontie',
    'Anesthésiologie',
    'Oto-rhino-laryngologie',
    'Angiologie',
    'Médecine légale',
    'Gastroentérologie',
    'Rhumatologie',
    'Médecine dentaire reconstructive',
    'Chirurgie',
    'Médecine physique et réadaptation',
    'Urologie',
    'Oncologie médicale',
    'Endocrinologie-diabétologie',
    'Chirurgie orale',
    'Neurochirurgie',
    'Chirurgie maxillo-faciale',
    'Hématologie',
    'Médecine nucléaire',
    'Radiologie',
    'Soins intensifs',
    'Néphrologie',
    'Prévention et santé publique',
    'Chirurgie de la main',
    'Infectiologie',
    'Radio-oncologie/radiothérapie',
    'Génétique médicale',
    'Pathologie',
    'Pharmacologie et toxicologie cliniques',
];
